<?php

/**
 * Base class that represents a row from the 'serie' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Mon Mar 19 16:27:22 2012
 *
 * @package    lib.model.om
 */
abstract class BaseSerie extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        SeriePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the realisateur_id field.
	 * @var        int
	 */
	protected $realisateur_id;

	/**
	 * The value for the titre field.
	 * @var        string
	 */
	protected $titre;

	/**
	 * The value for the sous_titre field.
	 * @var        string
	 */
	protected $sous_titre;

	/**
	 * The value for the titre_original field.
	 * @var        string
	 */
	protected $titre_original;

	/**
	 * The value for the titre_clean field.
	 * @var        string
	 */
	protected $titre_clean;

	/**
	 * The value for the bande_annonce field.
	 * @var        string
	 */
	protected $bande_annonce;

	/**
	 * The value for the image field.
	 * @var        string
	 */
	protected $image;

	/**
	 * The value for the resume field.
	 * @var        string
	 */
	protected $resume;

	/**
	 * The value for the annee_diffusion field.
	 * @var        string
	 */
	protected $annee_diffusion;

	/**
	 * The value for the format_duree field.
	 * @var        int
	 */
	protected $format_duree;

	/**
	 * The value for the is_public field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $is_public;

	/**
	 * The value for the nb_visite field.
	 * @var        int
	 */
	protected $nb_visite;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        Personne
	 */
	protected $aPersonne;

	/**
	 * @var        array Saison[] Collection to store aggregation of Saison objects.
	 */
	protected $collSaisons;

	/**
	 * @var        Criteria The criteria used to select the current contents of collSaisons.
	 */
	private $lastSaisonCriteria = null;

	/**
	 * @var        array Categorieserie[] Collection to store aggregation of Categorieserie objects.
	 */
	protected $collCategorieseries;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCategorieseries.
	 */
	private $lastCategorieserieCriteria = null;

	/**
	 * @var        array Serieproprietaire[] Collection to store aggregation of Serieproprietaire objects.
	 */
	protected $collSerieproprietaires;

	/**
	 * @var        Criteria The criteria used to select the current contents of collSerieproprietaires.
	 */
	private $lastSerieproprietaireCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'SeriePeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->is_public = true;
	}

	/**
	 * Initializes internal state of BaseSerie object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [realisateur_id] column value.
	 * 
	 * @return     int
	 */
	public function getRealisateurId()
	{
		return $this->realisateur_id;
	}

	/**
	 * Get the [titre] column value.
	 * 
	 * @return     string
	 */
	public function getTitre()
	{
		return $this->titre;
	}

	/**
	 * Get the [sous_titre] column value.
	 * 
	 * @return     string
	 */
	public function getSousTitre()
	{
		return $this->sous_titre;
	}

	/**
	 * Get the [titre_original] column value.
	 * 
	 * @return     string
	 */
	public function getTitreOriginal()
	{
		return $this->titre_original;
	}

	/**
	 * Get the [titre_clean] column value.
	 * 
	 * @return     string
	 */
	public function getTitreClean()
	{
		return $this->titre_clean;
	}

	/**
	 * Get the [bande_annonce] column value.
	 * 
	 * @return     string
	 */
	public function getBandeAnnonce()
	{
		return $this->bande_annonce;
	}

	/**
	 * Get the [image] column value.
	 * 
	 * @return     string
	 */
	public function getImage()
	{
		return $this->image;
	}

	/**
	 * Get the [resume] column value.
	 * 
	 * @return     string
	 */
	public function getResume()
	{
		return $this->resume;
	}

	/**
	 * Get the [annee_diffusion] column value.
	 * 
	 * @return     string
	 */
	public function getAnneeDiffusion()
	{
		return $this->annee_diffusion;
	}

	/**
	 * Get the [format_duree] column value.
	 * 
	 * @return     int
	 */
	public function getFormatDuree()
	{
		return $this->format_duree;
	}

	/**
	 * Get the [is_public] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsPublic()
	{
		return $this->is_public;
	}

	/**
	 * Get the [nb_visite] column value.
	 * 
	 * @return     int
	 */
	public function getNbVisite()
	{
		return $this->nb_visite;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Serie The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = SeriePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [realisateur_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Serie The current object (for fluent API support)
	 */
	public function setRealisateurId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->realisateur_id !== $v) {
			$this->realisateur_id = $v;
			$this->modifiedColumns[] = SeriePeer::REALISATEUR_ID;
		}

		if ($this->aPersonne !== null && $this->aPersonne->getId() !== $v) {
			$this->aPersonne = null;
		}

		return $this;
	} // setRealisateurId()

	/**
	 * Set the value of [titre] column.
	 * 
	 * @param      string $v new value
	 * @return     Serie The current object (for fluent API support)
	 */
	public function setTitre($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->titre !== $v) {
			$this->titre = $v;
			$this->modifiedColumns[] = SeriePeer::TITRE;
		}

		return $this;
	} // setTitre()

	/**
	 * Set the value of [sous_titre] column.
	 * 
	 * @param      string $v new value
	 * @return     Serie The current object (for fluent API support)
	 */
	public function setSousTitre($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->sous_titre !== $v) {
			$this->sous_titre = $v;
			$this->modifiedColumns[] = SeriePeer::SOUS_TITRE;
		}

		return $this;
	} // setSousTitre()

	/**
	 * Set the value of [titre_original] column.
	 * 
	 * @param      string $v new value
	 * @return     Serie The current object (for fluent API support)
	 */
	public function setTitreOriginal($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->titre_original !== $v) {
			$this->titre_original = $v;
			$this->modifiedColumns[] = SeriePeer::TITRE_ORIGINAL;
		}

		return $this;
	} // setTitreOriginal()

	/**
	 * Set the value of [titre_clean] column.
	 * 
	 * @param      string $v new value
	 * @return     Serie The current object (for fluent API support)
	 */
	public function setTitreClean($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->titre_clean !== $v) {
			$this->titre_clean = $v;
			$this->modifiedColumns[] = SeriePeer::TITRE_CLEAN;
		}

		return $this;
	} // setTitreClean()

	/**
	 * Set the value of [bande_annonce] column.
	 * 
	 * @param      string $v new value
	 * @return     Serie The current object (for fluent API support)
	 */
	public function setBandeAnnonce($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->bande_annonce !== $v) {
			$this->bande_annonce = $v;
			$this->modifiedColumns[] = SeriePeer::BANDE_ANNONCE;
		}

		return $this;
	} // setBandeAnnonce()

	/**
	 * Set the value of [image] column.
	 * 
	 * @param      string $v new value
	 * @return     Serie The current object (for fluent API support)
	 */
	public function setImage($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->image !== $v) {
			$this->image = $v;
			$this->modifiedColumns[] = SeriePeer::IMAGE;
		}

		return $this;
	} // setImage()

	/**
	 * Set the value of [resume] column.
	 * 
	 * @param      string $v new value
	 * @return     Serie The current object (for fluent API support)
	 */
	public function setResume($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->resume !== $v) {
			$this->resume = $v;
			$this->modifiedColumns[] = SeriePeer::RESUME;
		}

		return $this;
	} // setResume()

	/**
	 * Set the value of [annee_diffusion] column.
	 * 
	 * @param      string $v new value
	 * @return     Serie The current object (for fluent API support)
	 */
	public function setAnneeDiffusion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->annee_diffusion !== $v) {
			$this->annee_diffusion = $v;
			$this->modifiedColumns[] = SeriePeer::ANNEE_DIFFUSION;
		}

		return $this;
	} // setAnneeDiffusion()

	/**
	 * Set the value of [format_duree] column.
	 * 
	 * @param      int $v new value
	 * @return     Serie The current object (for fluent API support)
	 */
	public function setFormatDuree($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->format_duree !== $v) {
			$this->format_duree = $v;
			$this->modifiedColumns[] = SeriePeer::FORMAT_DUREE;
		}

		return $this;
	} // setFormatDuree()

	/**
	 * Set the value of [is_public] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Serie The current object (for fluent API support)
	 */
	public function setIsPublic($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_public !== $v || $this->isNew()) {
			$this->is_public = $v;
			$this->modifiedColumns[] = SeriePeer::IS_PUBLIC;
		}

		return $this;
	} // setIsPublic()

	/**
	 * Set the value of [nb_visite] column.
	 * 
	 * @param      int $v new value
	 * @return     Serie The current object (for fluent API support)
	 */
	public function setNbVisite($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->nb_visite !== $v) {
			$this->nb_visite = $v;
			$this->modifiedColumns[] = SeriePeer::NB_VISITE;
		}

		return $this;
	} // setNbVisite()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Serie The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = SeriePeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Serie The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = SeriePeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->is_public !== true) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->realisateur_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->titre = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->sous_titre = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->titre_original = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->titre_clean = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->bande_annonce = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->image = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->resume = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->annee_diffusion = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->format_duree = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->is_public = ($row[$startcol + 11] !== null) ? (boolean) $row[$startcol + 11] : null;
			$this->nb_visite = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->created_at = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->updated_at = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 15; // 15 = SeriePeer::NUM_COLUMNS - SeriePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Serie object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aPersonne !== null && $this->realisateur_id !== $this->aPersonne->getId()) {
			$this->aPersonne = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SeriePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = SeriePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aPersonne = null;
			$this->collSaisons = null;
			$this->lastSaisonCriteria = null;

			$this->collCategorieseries = null;
			$this->lastCategorieserieCriteria = null;

			$this->collSerieproprietaires = null;
			$this->lastSerieproprietaireCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SeriePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseSerie:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				SeriePeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseSerie:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SeriePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseSerie:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(SeriePeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(SeriePeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseSerie:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				SeriePeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPersonne !== null) {
				if ($this->aPersonne->isModified() || $this->aPersonne->isNew()) {
					$affectedRows += $this->aPersonne->save($con);
				}
				$this->setPersonne($this->aPersonne);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = SeriePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = SeriePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += SeriePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collSaisons !== null) {
				foreach ($this->collSaisons as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collCategorieseries !== null) {
				foreach ($this->collCategorieseries as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collSerieproprietaires !== null) {
				foreach ($this->collSerieproprietaires as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPersonne !== null) {
				if (!$this->aPersonne->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPersonne->getValidationFailures());
				}
			}


			if (($retval = SeriePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collSaisons !== null) {
					foreach ($this->collSaisons as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collCategorieseries !== null) {
					foreach ($this->collCategorieseries as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collSerieproprietaires !== null) {
					foreach ($this->collSerieproprietaires as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = SeriePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getRealisateurId();
				break;
			case 2:
				return $this->getTitre();
				break;
			case 3:
				return $this->getSousTitre();
				break;
			case 4:
				return $this->getTitreOriginal();
				break;
			case 5:
				return $this->getTitreClean();
				break;
			case 6:
				return $this->getBandeAnnonce();
				break;
			case 7:
				return $this->getImage();
				break;
			case 8:
				return $this->getResume();
				break;
			case 9:
				return $this->getAnneeDiffusion();
				break;
			case 10:
				return $this->getFormatDuree();
				break;
			case 11:
				return $this->getIsPublic();
				break;
			case 12:
				return $this->getNbVisite();
				break;
			case 13:
				return $this->getCreatedAt();
				break;
			case 14:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = SeriePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getRealisateurId(),
			$keys[2] => $this->getTitre(),
			$keys[3] => $this->getSousTitre(),
			$keys[4] => $this->getTitreOriginal(),
			$keys[5] => $this->getTitreClean(),
			$keys[6] => $this->getBandeAnnonce(),
			$keys[7] => $this->getImage(),
			$keys[8] => $this->getResume(),
			$keys[9] => $this->getAnneeDiffusion(),
			$keys[10] => $this->getFormatDuree(),
			$keys[11] => $this->getIsPublic(),
			$keys[12] => $this->getNbVisite(),
			$keys[13] => $this->getCreatedAt(),
			$keys[14] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = SeriePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setRealisateurId($value);
				break;
			case 2:
				$this->setTitre($value);
				break;
			case 3:
				$this->setSousTitre($value);
				break;
			case 4:
				$this->setTitreOriginal($value);
				break;
			case 5:
				$this->setTitreClean($value);
				break;
			case 6:
				$this->setBandeAnnonce($value);
				break;
			case 7:
				$this->setImage($value);
				break;
			case 8:
				$this->setResume($value);
				break;
			case 9:
				$this->setAnneeDiffusion($value);
				break;
			case 10:
				$this->setFormatDuree($value);
				break;
			case 11:
				$this->setIsPublic($value);
				break;
			case 12:
				$this->setNbVisite($value);
				break;
			case 13:
				$this->setCreatedAt($value);
				break;
			case 14:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = SeriePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setRealisateurId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setTitre($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setSousTitre($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setTitreOriginal($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setTitreClean($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setBandeAnnonce($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setImage($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setResume($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setAnneeDiffusion($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setFormatDuree($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setIsPublic($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setNbVisite($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setCreatedAt($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setUpdatedAt($arr[$keys[14]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(SeriePeer::DATABASE_NAME);

		if ($this->isColumnModified(SeriePeer::ID)) $criteria->add(SeriePeer::ID, $this->id);
		if ($this->isColumnModified(SeriePeer::REALISATEUR_ID)) $criteria->add(SeriePeer::REALISATEUR_ID, $this->realisateur_id);
		if ($this->isColumnModified(SeriePeer::TITRE)) $criteria->add(SeriePeer::TITRE, $this->titre);
		if ($this->isColumnModified(SeriePeer::SOUS_TITRE)) $criteria->add(SeriePeer::SOUS_TITRE, $this->sous_titre);
		if ($this->isColumnModified(SeriePeer::TITRE_ORIGINAL)) $criteria->add(SeriePeer::TITRE_ORIGINAL, $this->titre_original);
		if ($this->isColumnModified(SeriePeer::TITRE_CLEAN)) $criteria->add(SeriePeer::TITRE_CLEAN, $this->titre_clean);
		if ($this->isColumnModified(SeriePeer::BANDE_ANNONCE)) $criteria->add(SeriePeer::BANDE_ANNONCE, $this->bande_annonce);
		if ($this->isColumnModified(SeriePeer::IMAGE)) $criteria->add(SeriePeer::IMAGE, $this->image);
		if ($this->isColumnModified(SeriePeer::RESUME)) $criteria->add(SeriePeer::RESUME, $this->resume);
		if ($this->isColumnModified(SeriePeer::ANNEE_DIFFUSION)) $criteria->add(SeriePeer::ANNEE_DIFFUSION, $this->annee_diffusion);
		if ($this->isColumnModified(SeriePeer::FORMAT_DUREE)) $criteria->add(SeriePeer::FORMAT_DUREE, $this->format_duree);
		if ($this->isColumnModified(SeriePeer::IS_PUBLIC)) $criteria->add(SeriePeer::IS_PUBLIC, $this->is_public);
		if ($this->isColumnModified(SeriePeer::NB_VISITE)) $criteria->add(SeriePeer::NB_VISITE, $this->nb_visite);
		if ($this->isColumnModified(SeriePeer::CREATED_AT)) $criteria->add(SeriePeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(SeriePeer::UPDATED_AT)) $criteria->add(SeriePeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(SeriePeer::DATABASE_NAME);

		$criteria->add(SeriePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Serie (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setRealisateurId($this->realisateur_id);

		$copyObj->setTitre($this->titre);

		$copyObj->setSousTitre($this->sous_titre);

		$copyObj->setTitreOriginal($this->titre_original);

		$copyObj->setTitreClean($this->titre_clean);

		$copyObj->setBandeAnnonce($this->bande_annonce);

		$copyObj->setImage($this->image);

		$copyObj->setResume($this->resume);

		$copyObj->setAnneeDiffusion($this->annee_diffusion);

		$copyObj->setFormatDuree($this->format_duree);

		$copyObj->setIsPublic($this->is_public);

		$copyObj->setNbVisite($this->nb_visite);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getSaisons() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addSaison($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getCategorieseries() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCategorieserie($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getSerieproprietaires() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addSerieproprietaire($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Serie Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     SeriePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new SeriePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Personne object.
	 *
	 * @param      Personne $v
	 * @return     Serie The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPersonne(Personne $v = null)
	{
		if ($v === null) {
			$this->setRealisateurId(NULL);
		} else {
			$this->setRealisateurId($v->getId());
		}

		$this->aPersonne = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Personne object, it will not be re-added.
		if ($v !== null) {
			$v->addSerie($this);
		}

		return $this;
	}


	/**
	 * Get the associated Personne object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Personne The associated Personne object.
	 * @throws     PropelException
	 */
	public function getPersonne(PropelPDO $con = null)
	{
		if ($this->aPersonne === null && ($this->realisateur_id !== null)) {
			$this->aPersonne = PersonnePeer::retrieveByPk($this->realisateur_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPersonne->addSeries($this);
			 */
		}
		return $this->aPersonne;
	}

	/**
	 * Clears out the collSaisons collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addSaisons()
	 */
	public function clearSaisons()
	{
		$this->collSaisons = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collSaisons collection (array).
	 *
	 * By default this just sets the collSaisons collection to an empty array (like clearcollSaisons());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initSaisons()
	{
		$this->collSaisons = array();
	}

	/**
	 * Gets an array of Saison objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Serie has previously been saved, it will retrieve
	 * related Saisons from storage. If this Serie is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Saison[]
	 * @throws     PropelException
	 */
	public function getSaisons($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SeriePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSaisons === null) {
			if ($this->isNew()) {
			   $this->collSaisons = array();
			} else {

				$criteria->add(SaisonPeer::SERIE_ID, $this->id);

				SaisonPeer::addSelectColumns($criteria);
				$this->collSaisons = SaisonPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(SaisonPeer::SERIE_ID, $this->id);

				SaisonPeer::addSelectColumns($criteria);
				if (!isset($this->lastSaisonCriteria) || !$this->lastSaisonCriteria->equals($criteria)) {
					$this->collSaisons = SaisonPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastSaisonCriteria = $criteria;
		return $this->collSaisons;
	}

	/**
	 * Returns the number of related Saison objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Saison objects.
	 * @throws     PropelException
	 */
	public function countSaisons(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SeriePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collSaisons === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(SaisonPeer::SERIE_ID, $this->id);

				$count = SaisonPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(SaisonPeer::SERIE_ID, $this->id);

				if (!isset($this->lastSaisonCriteria) || !$this->lastSaisonCriteria->equals($criteria)) {
					$count = SaisonPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collSaisons);
				}
			} else {
				$count = count($this->collSaisons);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Saison object to this object
	 * through the Saison foreign key attribute.
	 *
	 * @param      Saison $l Saison
	 * @return     void
	 * @throws     PropelException
	 */
	public function addSaison(Saison $l)
	{
		if ($this->collSaisons === null) {
			$this->initSaisons();
		}
		if (!in_array($l, $this->collSaisons, true)) { // only add it if the **same** object is not already associated
			array_push($this->collSaisons, $l);
			$l->setSerie($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Serie is new, it will return
	 * an empty collection; or if this Serie has previously
	 * been saved, it will retrieve related Saisons from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Serie.
	 */
	public function getSaisonsJoinPersonne($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SeriePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSaisons === null) {
			if ($this->isNew()) {
				$this->collSaisons = array();
			} else {

				$criteria->add(SaisonPeer::SERIE_ID, $this->id);

				$this->collSaisons = SaisonPeer::doSelectJoinPersonne($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SaisonPeer::SERIE_ID, $this->id);

			if (!isset($this->lastSaisonCriteria) || !$this->lastSaisonCriteria->equals($criteria)) {
				$this->collSaisons = SaisonPeer::doSelectJoinPersonne($criteria, $con, $join_behavior);
			}
		}
		$this->lastSaisonCriteria = $criteria;

		return $this->collSaisons;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Serie is new, it will return
	 * an empty collection; or if this Serie has previously
	 * been saved, it will retrieve related Saisons from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Serie.
	 */
	public function getSaisonsJoinVersion($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SeriePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSaisons === null) {
			if ($this->isNew()) {
				$this->collSaisons = array();
			} else {

				$criteria->add(SaisonPeer::SERIE_ID, $this->id);

				$this->collSaisons = SaisonPeer::doSelectJoinVersion($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SaisonPeer::SERIE_ID, $this->id);

			if (!isset($this->lastSaisonCriteria) || !$this->lastSaisonCriteria->equals($criteria)) {
				$this->collSaisons = SaisonPeer::doSelectJoinVersion($criteria, $con, $join_behavior);
			}
		}
		$this->lastSaisonCriteria = $criteria;

		return $this->collSaisons;
	}

	/**
	 * Clears out the collCategorieseries collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCategorieseries()
	 */
	public function clearCategorieseries()
	{
		$this->collCategorieseries = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCategorieseries collection (array).
	 *
	 * By default this just sets the collCategorieseries collection to an empty array (like clearcollCategorieseries());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCategorieseries()
	{
		$this->collCategorieseries = array();
	}

	/**
	 * Gets an array of Categorieserie objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Serie has previously been saved, it will retrieve
	 * related Categorieseries from storage. If this Serie is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Categorieserie[]
	 * @throws     PropelException
	 */
	public function getCategorieseries($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SeriePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCategorieseries === null) {
			if ($this->isNew()) {
			   $this->collCategorieseries = array();
			} else {

				$criteria->add(CategorieseriePeer::SERIE_ID, $this->id);

				CategorieseriePeer::addSelectColumns($criteria);
				$this->collCategorieseries = CategorieseriePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CategorieseriePeer::SERIE_ID, $this->id);

				CategorieseriePeer::addSelectColumns($criteria);
				if (!isset($this->lastCategorieserieCriteria) || !$this->lastCategorieserieCriteria->equals($criteria)) {
					$this->collCategorieseries = CategorieseriePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCategorieserieCriteria = $criteria;
		return $this->collCategorieseries;
	}

	/**
	 * Returns the number of related Categorieserie objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Categorieserie objects.
	 * @throws     PropelException
	 */
	public function countCategorieseries(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SeriePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCategorieseries === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CategorieseriePeer::SERIE_ID, $this->id);

				$count = CategorieseriePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CategorieseriePeer::SERIE_ID, $this->id);

				if (!isset($this->lastCategorieserieCriteria) || !$this->lastCategorieserieCriteria->equals($criteria)) {
					$count = CategorieseriePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collCategorieseries);
				}
			} else {
				$count = count($this->collCategorieseries);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Categorieserie object to this object
	 * through the Categorieserie foreign key attribute.
	 *
	 * @param      Categorieserie $l Categorieserie
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCategorieserie(Categorieserie $l)
	{
		if ($this->collCategorieseries === null) {
			$this->initCategorieseries();
		}
		if (!in_array($l, $this->collCategorieseries, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCategorieseries, $l);
			$l->setSerie($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Serie is new, it will return
	 * an empty collection; or if this Serie has previously
	 * been saved, it will retrieve related Categorieseries from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Serie.
	 */
	public function getCategorieseriesJoinCategorie($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SeriePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCategorieseries === null) {
			if ($this->isNew()) {
				$this->collCategorieseries = array();
			} else {

				$criteria->add(CategorieseriePeer::SERIE_ID, $this->id);

				$this->collCategorieseries = CategorieseriePeer::doSelectJoinCategorie($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CategorieseriePeer::SERIE_ID, $this->id);

			if (!isset($this->lastCategorieserieCriteria) || !$this->lastCategorieserieCriteria->equals($criteria)) {
				$this->collCategorieseries = CategorieseriePeer::doSelectJoinCategorie($criteria, $con, $join_behavior);
			}
		}
		$this->lastCategorieserieCriteria = $criteria;

		return $this->collCategorieseries;
	}

	/**
	 * Clears out the collSerieproprietaires collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addSerieproprietaires()
	 */
	public function clearSerieproprietaires()
	{
		$this->collSerieproprietaires = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collSerieproprietaires collection (array).
	 *
	 * By default this just sets the collSerieproprietaires collection to an empty array (like clearcollSerieproprietaires());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initSerieproprietaires()
	{
		$this->collSerieproprietaires = array();
	}

	/**
	 * Gets an array of Serieproprietaire objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Serie has previously been saved, it will retrieve
	 * related Serieproprietaires from storage. If this Serie is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Serieproprietaire[]
	 * @throws     PropelException
	 */
	public function getSerieproprietaires($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SeriePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSerieproprietaires === null) {
			if ($this->isNew()) {
			   $this->collSerieproprietaires = array();
			} else {

				$criteria->add(SerieproprietairePeer::SERIE_ID, $this->id);

				SerieproprietairePeer::addSelectColumns($criteria);
				$this->collSerieproprietaires = SerieproprietairePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(SerieproprietairePeer::SERIE_ID, $this->id);

				SerieproprietairePeer::addSelectColumns($criteria);
				if (!isset($this->lastSerieproprietaireCriteria) || !$this->lastSerieproprietaireCriteria->equals($criteria)) {
					$this->collSerieproprietaires = SerieproprietairePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastSerieproprietaireCriteria = $criteria;
		return $this->collSerieproprietaires;
	}

	/**
	 * Returns the number of related Serieproprietaire objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Serieproprietaire objects.
	 * @throws     PropelException
	 */
	public function countSerieproprietaires(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SeriePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collSerieproprietaires === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(SerieproprietairePeer::SERIE_ID, $this->id);

				$count = SerieproprietairePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(SerieproprietairePeer::SERIE_ID, $this->id);

				if (!isset($this->lastSerieproprietaireCriteria) || !$this->lastSerieproprietaireCriteria->equals($criteria)) {
					$count = SerieproprietairePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collSerieproprietaires);
				}
			} else {
				$count = count($this->collSerieproprietaires);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Serieproprietaire object to this object
	 * through the Serieproprietaire foreign key attribute.
	 *
	 * @param      Serieproprietaire $l Serieproprietaire
	 * @return     void
	 * @throws     PropelException
	 */
	public function addSerieproprietaire(Serieproprietaire $l)
	{
		if ($this->collSerieproprietaires === null) {
			$this->initSerieproprietaires();
		}
		if (!in_array($l, $this->collSerieproprietaires, true)) { // only add it if the **same** object is not already associated
			array_push($this->collSerieproprietaires, $l);
			$l->setSerie($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Serie is new, it will return
	 * an empty collection; or if this Serie has previously
	 * been saved, it will retrieve related Serieproprietaires from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Serie.
	 */
	public function getSerieproprietairesJoinsfGuardUser($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SeriePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSerieproprietaires === null) {
			if ($this->isNew()) {
				$this->collSerieproprietaires = array();
			} else {

				$criteria->add(SerieproprietairePeer::SERIE_ID, $this->id);

				$this->collSerieproprietaires = SerieproprietairePeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SerieproprietairePeer::SERIE_ID, $this->id);

			if (!isset($this->lastSerieproprietaireCriteria) || !$this->lastSerieproprietaireCriteria->equals($criteria)) {
				$this->collSerieproprietaires = SerieproprietairePeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		}
		$this->lastSerieproprietaireCriteria = $criteria;

		return $this->collSerieproprietaires;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collSaisons) {
				foreach ((array) $this->collSaisons as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collCategorieseries) {
				foreach ((array) $this->collCategorieseries as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collSerieproprietaires) {
				foreach ((array) $this->collSerieproprietaires as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collSaisons = null;
		$this->collCategorieseries = null;
		$this->collSerieproprietaires = null;
			$this->aPersonne = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseSerie:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseSerie::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseSerie
