<?php

/**
 * Base class that represents a row from the 'personne' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Mon Mar 19 16:27:20 2012
 *
 * @package    lib.model.om
 */
abstract class BasePersonne extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        PersonnePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the nom field.
	 * @var        string
	 */
	protected $nom;

	/**
	 * The value for the prenom field.
	 * @var        string
	 */
	protected $prenom;

	/**
	 * The value for the nom_prenom_clean field.
	 * @var        string
	 */
	protected $nom_prenom_clean;

	/**
	 * The value for the image field.
	 * @var        string
	 */
	protected $image;

	/**
	 * The value for the date_naissance field.
	 * @var        string
	 */
	protected $date_naissance;

	/**
	 * The value for the date_deces field.
	 * @var        string
	 */
	protected $date_deces;

	/**
	 * The value for the nb_visite field.
	 * @var        int
	 */
	protected $nb_visite;

	/**
	 * The value for the nationalite_id field.
	 * @var        int
	 */
	protected $nationalite_id;

	/**
	 * @var        Nationalite
	 */
	protected $aNationalite;

	/**
	 * @var        array Video[] Collection to store aggregation of Video objects.
	 */
	protected $collVideos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collVideos.
	 */
	private $lastVideoCriteria = null;

	/**
	 * @var        array Serie[] Collection to store aggregation of Serie objects.
	 */
	protected $collSeries;

	/**
	 * @var        Criteria The criteria used to select the current contents of collSeries.
	 */
	private $lastSerieCriteria = null;

	/**
	 * @var        array Saison[] Collection to store aggregation of Saison objects.
	 */
	protected $collSaisons;

	/**
	 * @var        Criteria The criteria used to select the current contents of collSaisons.
	 */
	private $lastSaisonCriteria = null;

	/**
	 * @var        array Commentaireacteur[] Collection to store aggregation of Commentaireacteur objects.
	 */
	protected $collCommentaireacteurs;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCommentaireacteurs.
	 */
	private $lastCommentaireacteurCriteria = null;

	/**
	 * @var        array Commentairerealisateur[] Collection to store aggregation of Commentairerealisateur objects.
	 */
	protected $collCommentairerealisateurs;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCommentairerealisateurs.
	 */
	private $lastCommentairerealisateurCriteria = null;

	/**
	 * @var        array Acteurvideo[] Collection to store aggregation of Acteurvideo objects.
	 */
	protected $collActeurvideos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collActeurvideos.
	 */
	private $lastActeurvideoCriteria = null;

	/**
	 * @var        array Acteurserie[] Collection to store aggregation of Acteurserie objects.
	 */
	protected $collActeurseries;

	/**
	 * @var        Criteria The criteria used to select the current contents of collActeurseries.
	 */
	private $lastActeurserieCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'PersonnePeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [nom] column value.
	 * 
	 * @return     string
	 */
	public function getNom()
	{
		return $this->nom;
	}

	/**
	 * Get the [prenom] column value.
	 * 
	 * @return     string
	 */
	public function getPrenom()
	{
		return $this->prenom;
	}

	/**
	 * Get the [nom_prenom_clean] column value.
	 * 
	 * @return     string
	 */
	public function getNomPrenomClean()
	{
		return $this->nom_prenom_clean;
	}

	/**
	 * Get the [image] column value.
	 * 
	 * @return     string
	 */
	public function getImage()
	{
		return $this->image;
	}

	/**
	 * Get the [optionally formatted] temporal [date_naissance] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDateNaissance($format = 'Y-m-d')
	{
		if ($this->date_naissance === null) {
			return null;
		}


		if ($this->date_naissance === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->date_naissance);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->date_naissance, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [date_deces] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDateDeces($format = 'Y-m-d')
	{
		if ($this->date_deces === null) {
			return null;
		}


		if ($this->date_deces === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->date_deces);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->date_deces, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [nb_visite] column value.
	 * 
	 * @return     int
	 */
	public function getNbVisite()
	{
		return $this->nb_visite;
	}

	/**
	 * Get the [nationalite_id] column value.
	 * 
	 * @return     int
	 */
	public function getNationaliteId()
	{
		return $this->nationalite_id;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Personne The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = PersonnePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [nom] column.
	 * 
	 * @param      string $v new value
	 * @return     Personne The current object (for fluent API support)
	 */
	public function setNom($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nom !== $v) {
			$this->nom = $v;
			$this->modifiedColumns[] = PersonnePeer::NOM;
		}

		return $this;
	} // setNom()

	/**
	 * Set the value of [prenom] column.
	 * 
	 * @param      string $v new value
	 * @return     Personne The current object (for fluent API support)
	 */
	public function setPrenom($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->prenom !== $v) {
			$this->prenom = $v;
			$this->modifiedColumns[] = PersonnePeer::PRENOM;
		}

		return $this;
	} // setPrenom()

	/**
	 * Set the value of [nom_prenom_clean] column.
	 * 
	 * @param      string $v new value
	 * @return     Personne The current object (for fluent API support)
	 */
	public function setNomPrenomClean($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nom_prenom_clean !== $v) {
			$this->nom_prenom_clean = $v;
			$this->modifiedColumns[] = PersonnePeer::NOM_PRENOM_CLEAN;
		}

		return $this;
	} // setNomPrenomClean()

	/**
	 * Set the value of [image] column.
	 * 
	 * @param      string $v new value
	 * @return     Personne The current object (for fluent API support)
	 */
	public function setImage($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->image !== $v) {
			$this->image = $v;
			$this->modifiedColumns[] = PersonnePeer::IMAGE;
		}

		return $this;
	} // setImage()

	/**
	 * Sets the value of [date_naissance] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Personne The current object (for fluent API support)
	 */
	public function setDateNaissance($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->date_naissance !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->date_naissance !== null && $tmpDt = new DateTime($this->date_naissance)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->date_naissance = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = PersonnePeer::DATE_NAISSANCE;
			}
		} // if either are not null

		return $this;
	} // setDateNaissance()

	/**
	 * Sets the value of [date_deces] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Personne The current object (for fluent API support)
	 */
	public function setDateDeces($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->date_deces !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->date_deces !== null && $tmpDt = new DateTime($this->date_deces)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->date_deces = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = PersonnePeer::DATE_DECES;
			}
		} // if either are not null

		return $this;
	} // setDateDeces()

	/**
	 * Set the value of [nb_visite] column.
	 * 
	 * @param      int $v new value
	 * @return     Personne The current object (for fluent API support)
	 */
	public function setNbVisite($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->nb_visite !== $v) {
			$this->nb_visite = $v;
			$this->modifiedColumns[] = PersonnePeer::NB_VISITE;
		}

		return $this;
	} // setNbVisite()

	/**
	 * Set the value of [nationalite_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Personne The current object (for fluent API support)
	 */
	public function setNationaliteId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->nationalite_id !== $v) {
			$this->nationalite_id = $v;
			$this->modifiedColumns[] = PersonnePeer::NATIONALITE_ID;
		}

		if ($this->aNationalite !== null && $this->aNationalite->getId() !== $v) {
			$this->aNationalite = null;
		}

		return $this;
	} // setNationaliteId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->nom = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->prenom = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->nom_prenom_clean = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->image = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->date_naissance = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->date_deces = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->nb_visite = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->nationalite_id = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 9; // 9 = PersonnePeer::NUM_COLUMNS - PersonnePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Personne object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aNationalite !== null && $this->nationalite_id !== $this->aNationalite->getId()) {
			$this->aNationalite = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PersonnePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = PersonnePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aNationalite = null;
			$this->collVideos = null;
			$this->lastVideoCriteria = null;

			$this->collSeries = null;
			$this->lastSerieCriteria = null;

			$this->collSaisons = null;
			$this->lastSaisonCriteria = null;

			$this->collCommentaireacteurs = null;
			$this->lastCommentaireacteurCriteria = null;

			$this->collCommentairerealisateurs = null;
			$this->lastCommentairerealisateurCriteria = null;

			$this->collActeurvideos = null;
			$this->lastActeurvideoCriteria = null;

			$this->collActeurseries = null;
			$this->lastActeurserieCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PersonnePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePersonne:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				PersonnePeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePersonne:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PersonnePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePersonne:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePersonne:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				PersonnePeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aNationalite !== null) {
				if ($this->aNationalite->isModified() || $this->aNationalite->isNew()) {
					$affectedRows += $this->aNationalite->save($con);
				}
				$this->setNationalite($this->aNationalite);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = PersonnePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = PersonnePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += PersonnePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collVideos !== null) {
				foreach ($this->collVideos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collSeries !== null) {
				foreach ($this->collSeries as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collSaisons !== null) {
				foreach ($this->collSaisons as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collCommentaireacteurs !== null) {
				foreach ($this->collCommentaireacteurs as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collCommentairerealisateurs !== null) {
				foreach ($this->collCommentairerealisateurs as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collActeurvideos !== null) {
				foreach ($this->collActeurvideos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collActeurseries !== null) {
				foreach ($this->collActeurseries as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aNationalite !== null) {
				if (!$this->aNationalite->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aNationalite->getValidationFailures());
				}
			}


			if (($retval = PersonnePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collVideos !== null) {
					foreach ($this->collVideos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collSeries !== null) {
					foreach ($this->collSeries as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collSaisons !== null) {
					foreach ($this->collSaisons as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collCommentaireacteurs !== null) {
					foreach ($this->collCommentaireacteurs as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collCommentairerealisateurs !== null) {
					foreach ($this->collCommentairerealisateurs as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collActeurvideos !== null) {
					foreach ($this->collActeurvideos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collActeurseries !== null) {
					foreach ($this->collActeurseries as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PersonnePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getNom();
				break;
			case 2:
				return $this->getPrenom();
				break;
			case 3:
				return $this->getNomPrenomClean();
				break;
			case 4:
				return $this->getImage();
				break;
			case 5:
				return $this->getDateNaissance();
				break;
			case 6:
				return $this->getDateDeces();
				break;
			case 7:
				return $this->getNbVisite();
				break;
			case 8:
				return $this->getNationaliteId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = PersonnePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getNom(),
			$keys[2] => $this->getPrenom(),
			$keys[3] => $this->getNomPrenomClean(),
			$keys[4] => $this->getImage(),
			$keys[5] => $this->getDateNaissance(),
			$keys[6] => $this->getDateDeces(),
			$keys[7] => $this->getNbVisite(),
			$keys[8] => $this->getNationaliteId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PersonnePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setNom($value);
				break;
			case 2:
				$this->setPrenom($value);
				break;
			case 3:
				$this->setNomPrenomClean($value);
				break;
			case 4:
				$this->setImage($value);
				break;
			case 5:
				$this->setDateNaissance($value);
				break;
			case 6:
				$this->setDateDeces($value);
				break;
			case 7:
				$this->setNbVisite($value);
				break;
			case 8:
				$this->setNationaliteId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = PersonnePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setNom($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setPrenom($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setNomPrenomClean($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setImage($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setDateNaissance($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setDateDeces($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setNbVisite($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setNationaliteId($arr[$keys[8]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(PersonnePeer::DATABASE_NAME);

		if ($this->isColumnModified(PersonnePeer::ID)) $criteria->add(PersonnePeer::ID, $this->id);
		if ($this->isColumnModified(PersonnePeer::NOM)) $criteria->add(PersonnePeer::NOM, $this->nom);
		if ($this->isColumnModified(PersonnePeer::PRENOM)) $criteria->add(PersonnePeer::PRENOM, $this->prenom);
		if ($this->isColumnModified(PersonnePeer::NOM_PRENOM_CLEAN)) $criteria->add(PersonnePeer::NOM_PRENOM_CLEAN, $this->nom_prenom_clean);
		if ($this->isColumnModified(PersonnePeer::IMAGE)) $criteria->add(PersonnePeer::IMAGE, $this->image);
		if ($this->isColumnModified(PersonnePeer::DATE_NAISSANCE)) $criteria->add(PersonnePeer::DATE_NAISSANCE, $this->date_naissance);
		if ($this->isColumnModified(PersonnePeer::DATE_DECES)) $criteria->add(PersonnePeer::DATE_DECES, $this->date_deces);
		if ($this->isColumnModified(PersonnePeer::NB_VISITE)) $criteria->add(PersonnePeer::NB_VISITE, $this->nb_visite);
		if ($this->isColumnModified(PersonnePeer::NATIONALITE_ID)) $criteria->add(PersonnePeer::NATIONALITE_ID, $this->nationalite_id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(PersonnePeer::DATABASE_NAME);

		$criteria->add(PersonnePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Personne (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setNom($this->nom);

		$copyObj->setPrenom($this->prenom);

		$copyObj->setNomPrenomClean($this->nom_prenom_clean);

		$copyObj->setImage($this->image);

		$copyObj->setDateNaissance($this->date_naissance);

		$copyObj->setDateDeces($this->date_deces);

		$copyObj->setNbVisite($this->nb_visite);

		$copyObj->setNationaliteId($this->nationalite_id);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getVideos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addVideo($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getSeries() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addSerie($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getSaisons() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addSaison($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getCommentaireacteurs() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCommentaireacteur($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getCommentairerealisateurs() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCommentairerealisateur($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getActeurvideos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addActeurvideo($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getActeurseries() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addActeurserie($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Personne Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     PersonnePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new PersonnePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Nationalite object.
	 *
	 * @param      Nationalite $v
	 * @return     Personne The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setNationalite(Nationalite $v = null)
	{
		if ($v === null) {
			$this->setNationaliteId(NULL);
		} else {
			$this->setNationaliteId($v->getId());
		}

		$this->aNationalite = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Nationalite object, it will not be re-added.
		if ($v !== null) {
			$v->addPersonne($this);
		}

		return $this;
	}


	/**
	 * Get the associated Nationalite object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Nationalite The associated Nationalite object.
	 * @throws     PropelException
	 */
	public function getNationalite(PropelPDO $con = null)
	{
		if ($this->aNationalite === null && ($this->nationalite_id !== null)) {
			$this->aNationalite = NationalitePeer::retrieveByPk($this->nationalite_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aNationalite->addPersonnes($this);
			 */
		}
		return $this->aNationalite;
	}

	/**
	 * Clears out the collVideos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addVideos()
	 */
	public function clearVideos()
	{
		$this->collVideos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collVideos collection (array).
	 *
	 * By default this just sets the collVideos collection to an empty array (like clearcollVideos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initVideos()
	{
		$this->collVideos = array();
	}

	/**
	 * Gets an array of Video objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Personne has previously been saved, it will retrieve
	 * related Videos from storage. If this Personne is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Video[]
	 * @throws     PropelException
	 */
	public function getVideos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVideos === null) {
			if ($this->isNew()) {
			   $this->collVideos = array();
			} else {

				$criteria->add(VideoPeer::REALISATEUR_ID, $this->id);

				VideoPeer::addSelectColumns($criteria);
				$this->collVideos = VideoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(VideoPeer::REALISATEUR_ID, $this->id);

				VideoPeer::addSelectColumns($criteria);
				if (!isset($this->lastVideoCriteria) || !$this->lastVideoCriteria->equals($criteria)) {
					$this->collVideos = VideoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastVideoCriteria = $criteria;
		return $this->collVideos;
	}

	/**
	 * Returns the number of related Video objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Video objects.
	 * @throws     PropelException
	 */
	public function countVideos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collVideos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(VideoPeer::REALISATEUR_ID, $this->id);

				$count = VideoPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(VideoPeer::REALISATEUR_ID, $this->id);

				if (!isset($this->lastVideoCriteria) || !$this->lastVideoCriteria->equals($criteria)) {
					$count = VideoPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collVideos);
				}
			} else {
				$count = count($this->collVideos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Video object to this object
	 * through the Video foreign key attribute.
	 *
	 * @param      Video $l Video
	 * @return     void
	 * @throws     PropelException
	 */
	public function addVideo(Video $l)
	{
		if ($this->collVideos === null) {
			$this->initVideos();
		}
		if (!in_array($l, $this->collVideos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collVideos, $l);
			$l->setPersonne($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Personne is new, it will return
	 * an empty collection; or if this Personne has previously
	 * been saved, it will retrieve related Videos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Personne.
	 */
	public function getVideosJoinSaison($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVideos === null) {
			if ($this->isNew()) {
				$this->collVideos = array();
			} else {

				$criteria->add(VideoPeer::REALISATEUR_ID, $this->id);

				$this->collVideos = VideoPeer::doSelectJoinSaison($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(VideoPeer::REALISATEUR_ID, $this->id);

			if (!isset($this->lastVideoCriteria) || !$this->lastVideoCriteria->equals($criteria)) {
				$this->collVideos = VideoPeer::doSelectJoinSaison($criteria, $con, $join_behavior);
			}
		}
		$this->lastVideoCriteria = $criteria;

		return $this->collVideos;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Personne is new, it will return
	 * an empty collection; or if this Personne has previously
	 * been saved, it will retrieve related Videos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Personne.
	 */
	public function getVideosJoinSaga($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVideos === null) {
			if ($this->isNew()) {
				$this->collVideos = array();
			} else {

				$criteria->add(VideoPeer::REALISATEUR_ID, $this->id);

				$this->collVideos = VideoPeer::doSelectJoinSaga($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(VideoPeer::REALISATEUR_ID, $this->id);

			if (!isset($this->lastVideoCriteria) || !$this->lastVideoCriteria->equals($criteria)) {
				$this->collVideos = VideoPeer::doSelectJoinSaga($criteria, $con, $join_behavior);
			}
		}
		$this->lastVideoCriteria = $criteria;

		return $this->collVideos;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Personne is new, it will return
	 * an empty collection; or if this Personne has previously
	 * been saved, it will retrieve related Videos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Personne.
	 */
	public function getVideosJoinQualite($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVideos === null) {
			if ($this->isNew()) {
				$this->collVideos = array();
			} else {

				$criteria->add(VideoPeer::REALISATEUR_ID, $this->id);

				$this->collVideos = VideoPeer::doSelectJoinQualite($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(VideoPeer::REALISATEUR_ID, $this->id);

			if (!isset($this->lastVideoCriteria) || !$this->lastVideoCriteria->equals($criteria)) {
				$this->collVideos = VideoPeer::doSelectJoinQualite($criteria, $con, $join_behavior);
			}
		}
		$this->lastVideoCriteria = $criteria;

		return $this->collVideos;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Personne is new, it will return
	 * an empty collection; or if this Personne has previously
	 * been saved, it will retrieve related Videos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Personne.
	 */
	public function getVideosJoinVersion($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVideos === null) {
			if ($this->isNew()) {
				$this->collVideos = array();
			} else {

				$criteria->add(VideoPeer::REALISATEUR_ID, $this->id);

				$this->collVideos = VideoPeer::doSelectJoinVersion($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(VideoPeer::REALISATEUR_ID, $this->id);

			if (!isset($this->lastVideoCriteria) || !$this->lastVideoCriteria->equals($criteria)) {
				$this->collVideos = VideoPeer::doSelectJoinVersion($criteria, $con, $join_behavior);
			}
		}
		$this->lastVideoCriteria = $criteria;

		return $this->collVideos;
	}

	/**
	 * Clears out the collSeries collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addSeries()
	 */
	public function clearSeries()
	{
		$this->collSeries = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collSeries collection (array).
	 *
	 * By default this just sets the collSeries collection to an empty array (like clearcollSeries());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initSeries()
	{
		$this->collSeries = array();
	}

	/**
	 * Gets an array of Serie objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Personne has previously been saved, it will retrieve
	 * related Series from storage. If this Personne is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Serie[]
	 * @throws     PropelException
	 */
	public function getSeries($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSeries === null) {
			if ($this->isNew()) {
			   $this->collSeries = array();
			} else {

				$criteria->add(SeriePeer::REALISATEUR_ID, $this->id);

				SeriePeer::addSelectColumns($criteria);
				$this->collSeries = SeriePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(SeriePeer::REALISATEUR_ID, $this->id);

				SeriePeer::addSelectColumns($criteria);
				if (!isset($this->lastSerieCriteria) || !$this->lastSerieCriteria->equals($criteria)) {
					$this->collSeries = SeriePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastSerieCriteria = $criteria;
		return $this->collSeries;
	}

	/**
	 * Returns the number of related Serie objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Serie objects.
	 * @throws     PropelException
	 */
	public function countSeries(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collSeries === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(SeriePeer::REALISATEUR_ID, $this->id);

				$count = SeriePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(SeriePeer::REALISATEUR_ID, $this->id);

				if (!isset($this->lastSerieCriteria) || !$this->lastSerieCriteria->equals($criteria)) {
					$count = SeriePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collSeries);
				}
			} else {
				$count = count($this->collSeries);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Serie object to this object
	 * through the Serie foreign key attribute.
	 *
	 * @param      Serie $l Serie
	 * @return     void
	 * @throws     PropelException
	 */
	public function addSerie(Serie $l)
	{
		if ($this->collSeries === null) {
			$this->initSeries();
		}
		if (!in_array($l, $this->collSeries, true)) { // only add it if the **same** object is not already associated
			array_push($this->collSeries, $l);
			$l->setPersonne($this);
		}
	}

	/**
	 * Clears out the collSaisons collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addSaisons()
	 */
	public function clearSaisons()
	{
		$this->collSaisons = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collSaisons collection (array).
	 *
	 * By default this just sets the collSaisons collection to an empty array (like clearcollSaisons());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initSaisons()
	{
		$this->collSaisons = array();
	}

	/**
	 * Gets an array of Saison objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Personne has previously been saved, it will retrieve
	 * related Saisons from storage. If this Personne is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Saison[]
	 * @throws     PropelException
	 */
	public function getSaisons($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSaisons === null) {
			if ($this->isNew()) {
			   $this->collSaisons = array();
			} else {

				$criteria->add(SaisonPeer::REALISATEUR_ID, $this->id);

				SaisonPeer::addSelectColumns($criteria);
				$this->collSaisons = SaisonPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(SaisonPeer::REALISATEUR_ID, $this->id);

				SaisonPeer::addSelectColumns($criteria);
				if (!isset($this->lastSaisonCriteria) || !$this->lastSaisonCriteria->equals($criteria)) {
					$this->collSaisons = SaisonPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastSaisonCriteria = $criteria;
		return $this->collSaisons;
	}

	/**
	 * Returns the number of related Saison objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Saison objects.
	 * @throws     PropelException
	 */
	public function countSaisons(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collSaisons === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(SaisonPeer::REALISATEUR_ID, $this->id);

				$count = SaisonPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(SaisonPeer::REALISATEUR_ID, $this->id);

				if (!isset($this->lastSaisonCriteria) || !$this->lastSaisonCriteria->equals($criteria)) {
					$count = SaisonPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collSaisons);
				}
			} else {
				$count = count($this->collSaisons);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Saison object to this object
	 * through the Saison foreign key attribute.
	 *
	 * @param      Saison $l Saison
	 * @return     void
	 * @throws     PropelException
	 */
	public function addSaison(Saison $l)
	{
		if ($this->collSaisons === null) {
			$this->initSaisons();
		}
		if (!in_array($l, $this->collSaisons, true)) { // only add it if the **same** object is not already associated
			array_push($this->collSaisons, $l);
			$l->setPersonne($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Personne is new, it will return
	 * an empty collection; or if this Personne has previously
	 * been saved, it will retrieve related Saisons from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Personne.
	 */
	public function getSaisonsJoinSerie($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSaisons === null) {
			if ($this->isNew()) {
				$this->collSaisons = array();
			} else {

				$criteria->add(SaisonPeer::REALISATEUR_ID, $this->id);

				$this->collSaisons = SaisonPeer::doSelectJoinSerie($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SaisonPeer::REALISATEUR_ID, $this->id);

			if (!isset($this->lastSaisonCriteria) || !$this->lastSaisonCriteria->equals($criteria)) {
				$this->collSaisons = SaisonPeer::doSelectJoinSerie($criteria, $con, $join_behavior);
			}
		}
		$this->lastSaisonCriteria = $criteria;

		return $this->collSaisons;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Personne is new, it will return
	 * an empty collection; or if this Personne has previously
	 * been saved, it will retrieve related Saisons from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Personne.
	 */
	public function getSaisonsJoinVersion($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSaisons === null) {
			if ($this->isNew()) {
				$this->collSaisons = array();
			} else {

				$criteria->add(SaisonPeer::REALISATEUR_ID, $this->id);

				$this->collSaisons = SaisonPeer::doSelectJoinVersion($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SaisonPeer::REALISATEUR_ID, $this->id);

			if (!isset($this->lastSaisonCriteria) || !$this->lastSaisonCriteria->equals($criteria)) {
				$this->collSaisons = SaisonPeer::doSelectJoinVersion($criteria, $con, $join_behavior);
			}
		}
		$this->lastSaisonCriteria = $criteria;

		return $this->collSaisons;
	}

	/**
	 * Clears out the collCommentaireacteurs collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCommentaireacteurs()
	 */
	public function clearCommentaireacteurs()
	{
		$this->collCommentaireacteurs = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCommentaireacteurs collection (array).
	 *
	 * By default this just sets the collCommentaireacteurs collection to an empty array (like clearcollCommentaireacteurs());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCommentaireacteurs()
	{
		$this->collCommentaireacteurs = array();
	}

	/**
	 * Gets an array of Commentaireacteur objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Personne has previously been saved, it will retrieve
	 * related Commentaireacteurs from storage. If this Personne is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Commentaireacteur[]
	 * @throws     PropelException
	 */
	public function getCommentaireacteurs($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCommentaireacteurs === null) {
			if ($this->isNew()) {
			   $this->collCommentaireacteurs = array();
			} else {

				$criteria->add(CommentaireacteurPeer::ACTEUR_ID, $this->id);

				CommentaireacteurPeer::addSelectColumns($criteria);
				$this->collCommentaireacteurs = CommentaireacteurPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CommentaireacteurPeer::ACTEUR_ID, $this->id);

				CommentaireacteurPeer::addSelectColumns($criteria);
				if (!isset($this->lastCommentaireacteurCriteria) || !$this->lastCommentaireacteurCriteria->equals($criteria)) {
					$this->collCommentaireacteurs = CommentaireacteurPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCommentaireacteurCriteria = $criteria;
		return $this->collCommentaireacteurs;
	}

	/**
	 * Returns the number of related Commentaireacteur objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Commentaireacteur objects.
	 * @throws     PropelException
	 */
	public function countCommentaireacteurs(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCommentaireacteurs === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CommentaireacteurPeer::ACTEUR_ID, $this->id);

				$count = CommentaireacteurPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CommentaireacteurPeer::ACTEUR_ID, $this->id);

				if (!isset($this->lastCommentaireacteurCriteria) || !$this->lastCommentaireacteurCriteria->equals($criteria)) {
					$count = CommentaireacteurPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collCommentaireacteurs);
				}
			} else {
				$count = count($this->collCommentaireacteurs);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Commentaireacteur object to this object
	 * through the Commentaireacteur foreign key attribute.
	 *
	 * @param      Commentaireacteur $l Commentaireacteur
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCommentaireacteur(Commentaireacteur $l)
	{
		if ($this->collCommentaireacteurs === null) {
			$this->initCommentaireacteurs();
		}
		if (!in_array($l, $this->collCommentaireacteurs, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCommentaireacteurs, $l);
			$l->setPersonne($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Personne is new, it will return
	 * an empty collection; or if this Personne has previously
	 * been saved, it will retrieve related Commentaireacteurs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Personne.
	 */
	public function getCommentaireacteursJoinUtilisateur($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCommentaireacteurs === null) {
			if ($this->isNew()) {
				$this->collCommentaireacteurs = array();
			} else {

				$criteria->add(CommentaireacteurPeer::ACTEUR_ID, $this->id);

				$this->collCommentaireacteurs = CommentaireacteurPeer::doSelectJoinUtilisateur($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CommentaireacteurPeer::ACTEUR_ID, $this->id);

			if (!isset($this->lastCommentaireacteurCriteria) || !$this->lastCommentaireacteurCriteria->equals($criteria)) {
				$this->collCommentaireacteurs = CommentaireacteurPeer::doSelectJoinUtilisateur($criteria, $con, $join_behavior);
			}
		}
		$this->lastCommentaireacteurCriteria = $criteria;

		return $this->collCommentaireacteurs;
	}

	/**
	 * Clears out the collCommentairerealisateurs collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCommentairerealisateurs()
	 */
	public function clearCommentairerealisateurs()
	{
		$this->collCommentairerealisateurs = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCommentairerealisateurs collection (array).
	 *
	 * By default this just sets the collCommentairerealisateurs collection to an empty array (like clearcollCommentairerealisateurs());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCommentairerealisateurs()
	{
		$this->collCommentairerealisateurs = array();
	}

	/**
	 * Gets an array of Commentairerealisateur objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Personne has previously been saved, it will retrieve
	 * related Commentairerealisateurs from storage. If this Personne is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Commentairerealisateur[]
	 * @throws     PropelException
	 */
	public function getCommentairerealisateurs($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCommentairerealisateurs === null) {
			if ($this->isNew()) {
			   $this->collCommentairerealisateurs = array();
			} else {

				$criteria->add(CommentairerealisateurPeer::REALISATEUR_ID, $this->id);

				CommentairerealisateurPeer::addSelectColumns($criteria);
				$this->collCommentairerealisateurs = CommentairerealisateurPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CommentairerealisateurPeer::REALISATEUR_ID, $this->id);

				CommentairerealisateurPeer::addSelectColumns($criteria);
				if (!isset($this->lastCommentairerealisateurCriteria) || !$this->lastCommentairerealisateurCriteria->equals($criteria)) {
					$this->collCommentairerealisateurs = CommentairerealisateurPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCommentairerealisateurCriteria = $criteria;
		return $this->collCommentairerealisateurs;
	}

	/**
	 * Returns the number of related Commentairerealisateur objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Commentairerealisateur objects.
	 * @throws     PropelException
	 */
	public function countCommentairerealisateurs(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCommentairerealisateurs === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CommentairerealisateurPeer::REALISATEUR_ID, $this->id);

				$count = CommentairerealisateurPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CommentairerealisateurPeer::REALISATEUR_ID, $this->id);

				if (!isset($this->lastCommentairerealisateurCriteria) || !$this->lastCommentairerealisateurCriteria->equals($criteria)) {
					$count = CommentairerealisateurPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collCommentairerealisateurs);
				}
			} else {
				$count = count($this->collCommentairerealisateurs);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Commentairerealisateur object to this object
	 * through the Commentairerealisateur foreign key attribute.
	 *
	 * @param      Commentairerealisateur $l Commentairerealisateur
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCommentairerealisateur(Commentairerealisateur $l)
	{
		if ($this->collCommentairerealisateurs === null) {
			$this->initCommentairerealisateurs();
		}
		if (!in_array($l, $this->collCommentairerealisateurs, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCommentairerealisateurs, $l);
			$l->setPersonne($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Personne is new, it will return
	 * an empty collection; or if this Personne has previously
	 * been saved, it will retrieve related Commentairerealisateurs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Personne.
	 */
	public function getCommentairerealisateursJoinUtilisateur($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCommentairerealisateurs === null) {
			if ($this->isNew()) {
				$this->collCommentairerealisateurs = array();
			} else {

				$criteria->add(CommentairerealisateurPeer::REALISATEUR_ID, $this->id);

				$this->collCommentairerealisateurs = CommentairerealisateurPeer::doSelectJoinUtilisateur($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CommentairerealisateurPeer::REALISATEUR_ID, $this->id);

			if (!isset($this->lastCommentairerealisateurCriteria) || !$this->lastCommentairerealisateurCriteria->equals($criteria)) {
				$this->collCommentairerealisateurs = CommentairerealisateurPeer::doSelectJoinUtilisateur($criteria, $con, $join_behavior);
			}
		}
		$this->lastCommentairerealisateurCriteria = $criteria;

		return $this->collCommentairerealisateurs;
	}

	/**
	 * Clears out the collActeurvideos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addActeurvideos()
	 */
	public function clearActeurvideos()
	{
		$this->collActeurvideos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collActeurvideos collection (array).
	 *
	 * By default this just sets the collActeurvideos collection to an empty array (like clearcollActeurvideos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initActeurvideos()
	{
		$this->collActeurvideos = array();
	}

	/**
	 * Gets an array of Acteurvideo objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Personne has previously been saved, it will retrieve
	 * related Acteurvideos from storage. If this Personne is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Acteurvideo[]
	 * @throws     PropelException
	 */
	public function getActeurvideos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collActeurvideos === null) {
			if ($this->isNew()) {
			   $this->collActeurvideos = array();
			} else {

				$criteria->add(ActeurvideoPeer::ACTEUR_ID, $this->id);

				ActeurvideoPeer::addSelectColumns($criteria);
				$this->collActeurvideos = ActeurvideoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ActeurvideoPeer::ACTEUR_ID, $this->id);

				ActeurvideoPeer::addSelectColumns($criteria);
				if (!isset($this->lastActeurvideoCriteria) || !$this->lastActeurvideoCriteria->equals($criteria)) {
					$this->collActeurvideos = ActeurvideoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastActeurvideoCriteria = $criteria;
		return $this->collActeurvideos;
	}

	/**
	 * Returns the number of related Acteurvideo objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Acteurvideo objects.
	 * @throws     PropelException
	 */
	public function countActeurvideos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collActeurvideos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ActeurvideoPeer::ACTEUR_ID, $this->id);

				$count = ActeurvideoPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ActeurvideoPeer::ACTEUR_ID, $this->id);

				if (!isset($this->lastActeurvideoCriteria) || !$this->lastActeurvideoCriteria->equals($criteria)) {
					$count = ActeurvideoPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collActeurvideos);
				}
			} else {
				$count = count($this->collActeurvideos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Acteurvideo object to this object
	 * through the Acteurvideo foreign key attribute.
	 *
	 * @param      Acteurvideo $l Acteurvideo
	 * @return     void
	 * @throws     PropelException
	 */
	public function addActeurvideo(Acteurvideo $l)
	{
		if ($this->collActeurvideos === null) {
			$this->initActeurvideos();
		}
		if (!in_array($l, $this->collActeurvideos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collActeurvideos, $l);
			$l->setPersonne($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Personne is new, it will return
	 * an empty collection; or if this Personne has previously
	 * been saved, it will retrieve related Acteurvideos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Personne.
	 */
	public function getActeurvideosJoinVideo($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collActeurvideos === null) {
			if ($this->isNew()) {
				$this->collActeurvideos = array();
			} else {

				$criteria->add(ActeurvideoPeer::ACTEUR_ID, $this->id);

				$this->collActeurvideos = ActeurvideoPeer::doSelectJoinVideo($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ActeurvideoPeer::ACTEUR_ID, $this->id);

			if (!isset($this->lastActeurvideoCriteria) || !$this->lastActeurvideoCriteria->equals($criteria)) {
				$this->collActeurvideos = ActeurvideoPeer::doSelectJoinVideo($criteria, $con, $join_behavior);
			}
		}
		$this->lastActeurvideoCriteria = $criteria;

		return $this->collActeurvideos;
	}

	/**
	 * Clears out the collActeurseries collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addActeurseries()
	 */
	public function clearActeurseries()
	{
		$this->collActeurseries = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collActeurseries collection (array).
	 *
	 * By default this just sets the collActeurseries collection to an empty array (like clearcollActeurseries());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initActeurseries()
	{
		$this->collActeurseries = array();
	}

	/**
	 * Gets an array of Acteurserie objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Personne has previously been saved, it will retrieve
	 * related Acteurseries from storage. If this Personne is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Acteurserie[]
	 * @throws     PropelException
	 */
	public function getActeurseries($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collActeurseries === null) {
			if ($this->isNew()) {
			   $this->collActeurseries = array();
			} else {

				$criteria->add(ActeurseriePeer::ACTEUR_ID, $this->id);

				ActeurseriePeer::addSelectColumns($criteria);
				$this->collActeurseries = ActeurseriePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ActeurseriePeer::ACTEUR_ID, $this->id);

				ActeurseriePeer::addSelectColumns($criteria);
				if (!isset($this->lastActeurserieCriteria) || !$this->lastActeurserieCriteria->equals($criteria)) {
					$this->collActeurseries = ActeurseriePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastActeurserieCriteria = $criteria;
		return $this->collActeurseries;
	}

	/**
	 * Returns the number of related Acteurserie objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Acteurserie objects.
	 * @throws     PropelException
	 */
	public function countActeurseries(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collActeurseries === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ActeurseriePeer::ACTEUR_ID, $this->id);

				$count = ActeurseriePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ActeurseriePeer::ACTEUR_ID, $this->id);

				if (!isset($this->lastActeurserieCriteria) || !$this->lastActeurserieCriteria->equals($criteria)) {
					$count = ActeurseriePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collActeurseries);
				}
			} else {
				$count = count($this->collActeurseries);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Acteurserie object to this object
	 * through the Acteurserie foreign key attribute.
	 *
	 * @param      Acteurserie $l Acteurserie
	 * @return     void
	 * @throws     PropelException
	 */
	public function addActeurserie(Acteurserie $l)
	{
		if ($this->collActeurseries === null) {
			$this->initActeurseries();
		}
		if (!in_array($l, $this->collActeurseries, true)) { // only add it if the **same** object is not already associated
			array_push($this->collActeurseries, $l);
			$l->setPersonne($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Personne is new, it will return
	 * an empty collection; or if this Personne has previously
	 * been saved, it will retrieve related Acteurseries from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Personne.
	 */
	public function getActeurseriesJoinSaison($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PersonnePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collActeurseries === null) {
			if ($this->isNew()) {
				$this->collActeurseries = array();
			} else {

				$criteria->add(ActeurseriePeer::ACTEUR_ID, $this->id);

				$this->collActeurseries = ActeurseriePeer::doSelectJoinSaison($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ActeurseriePeer::ACTEUR_ID, $this->id);

			if (!isset($this->lastActeurserieCriteria) || !$this->lastActeurserieCriteria->equals($criteria)) {
				$this->collActeurseries = ActeurseriePeer::doSelectJoinSaison($criteria, $con, $join_behavior);
			}
		}
		$this->lastActeurserieCriteria = $criteria;

		return $this->collActeurseries;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collVideos) {
				foreach ((array) $this->collVideos as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collSeries) {
				foreach ((array) $this->collSeries as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collSaisons) {
				foreach ((array) $this->collSaisons as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collCommentaireacteurs) {
				foreach ((array) $this->collCommentaireacteurs as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collCommentairerealisateurs) {
				foreach ((array) $this->collCommentairerealisateurs as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collActeurvideos) {
				foreach ((array) $this->collActeurvideos as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collActeurseries) {
				foreach ((array) $this->collActeurseries as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collVideos = null;
		$this->collSeries = null;
		$this->collSaisons = null;
		$this->collCommentaireacteurs = null;
		$this->collCommentairerealisateurs = null;
		$this->collActeurvideos = null;
		$this->collActeurseries = null;
			$this->aNationalite = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BasePersonne:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BasePersonne::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BasePersonne
