<?php


/**
 * Skeleton subclass for representing a row from the 'ANOTHER_MODEL' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Jan  9 12:35:54 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AnotherModel extends BaseAnotherModel {

} // AnotherModel
