<?php


/**
 * Skeleton subclass for performing query and update operations on the 'categorievideo' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Mon Aug 29 11:15:03 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CategorievideoPeer extends BaseCategorievideoPeer {

} // CategorievideoPeer
