<?php


/**
 * Skeleton subclass for representing a row from the 'commentaireacteur' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 12/04/10 09:58:07
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Commentaireacteur extends BaseCommentaireacteur {

} // Commentaireacteur
