<?php


/**
 * Skeleton subclass for performing query and update operations on the 'utilisateur' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 12/04/10 09:58:06
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class UtilisateurPeer extends BaseUtilisateurPeer {

  public static function preAll($action) {
		$pro=$action->getUser()->getAttribute("proprio");
		$sauv=SauvegardeVisiteurPeer::getSauvegardeVisiteur($_SERVER['REMOTE_ADDR']);
		
		if($sauv){
			$sauv->setDerniereConnection(date('Y-m-d H:i:s'));
			$sauv->save();
			if($pro){
				if($pro->getId()!=$sauv->getProprioId()){
					$proprio = sfGuardUserPeer::retrieveByPk($sauv->getProprioId());
					$action->getUser()->setAttribute("proprio",$proprio);
				}
			}else{
				if($sauv->getProprioId()!=0){
					$proprio = sfGuardUserPeer::retrieveByPk($sauv->getProprioId());
					$action->getUser()->setAttribute("proprio",$proprio);
				}
			}
		}else{
			$sauv = new SauvegardeVisiteur();
			$sauv->setAdresse($_SERVER['REMOTE_ADDR']);
			$sauv->setDerniereConnection(date('Y-m-d H:i:s'));
			$sauv->save();
		}
		
        $nbfilms=VideoPeer::getNbFilms($pro);
        $action->getRequest()->setAttribute('nbfilms', $nbfilms);
        $nbspectacles=VideoPeer::getNbSpectacles($pro);
        $action->getRequest()->setAttribute('nbspectacles', $nbspectacles);

        $nbseries=SeriePeer::getNbSeries();
        $action->getRequest()->setAttribute('nbseries', $nbseries);
		
		
        $proprio=sfGuardUserPeer::getProprio();
        $action->getRequest()->setAttribute('proprio', $proprio);


        $dervideos = VideoPeer::getDerniersVideos($pro,10);
		
		$nb=sizeof($dervideos);
		for($i=0;$i<$nb;$i++){
			$indice = array_rand($dervideos);
			$dervideos2[] = $dervideos[$indice];
			unset($dervideos[$indice]);
		}
		
        $action->getRequest()->setAttribute('derVideo', $dervideos2);
		
        //$this->getRequest()->setAttribute('tab', $indice);
		
		
		if($action->getUser()->getAttribute("incorr")){
			$action->getRequest()->setAttribute('incorr', true);
			// supprime une variable de la session
			$action->getUser()->getAttributeHolder()->remove('incorr');
		}
  }

} // UtilisateurPeer
