<?php


/**
 * Skeleton subclass for performing query and update operations on the 'video' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Mon Aug 29 10:18:21 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
 
define('ALLOCINE_PARTNER_KEY', '100043982026');
define('ALLOCINE_SECRET_KEY', '29d185d98c984a359e6e6f26a0474269');
 
class VideoPeer extends BaseVideoPeer {

  static function array_to_obj($array, &$obj)
  {
    foreach ($array as $key => $value)
    {
      if (is_array($value))
      {
      $obj->$key = new stdClass();
      self::array_to_obj($value, $obj->$key);
      }
      else
      {
        $obj->$key = $value;
      }
    }
  return $obj;
  }

static function arrayToObject($array)
{
 $object= new stdClass();
 return self::array_to_obj($array,$object);
}




  static public function getLuceneIndex()
        {
          ProjectConfiguration::registerZend();

          if (file_exists($index = self::getLuceneIndexFile()))
          {
            return Zend_Search_Lucene::open($index);
          }
          else
          {
            $de= Zend_Search_Lucene::create($index);
            return $de;
          }
        }

        static public function getLuceneIndexFile()
        {
          return sfConfig::get('sf_data_dir').'/video.'.sfConfig::get('sf_environment').'.index';
        }


        static public function getForLuceneQuery($query)
        {
			$quer= $query;
          $hits = self::getLuceneIndex()->find($quer);
          $pks = array();
          foreach ($hits as $hit)
          {
            $pks[] = $hit->pk;
          }

          $criteria = new Criteria();
          $criteria->add(self::ID, $pks, Criteria::IN);
          $criteria->setLimit(20);

          return self::doSelect($criteria);
        }

        public static function doDeleteAll($con = null)
        {
          if (file_exists($index = self::getLuceneIndexFile()))
          {
            sfToolkit::clearDirectory($index);
            rmdir($index);
          }

          return parent::doDeleteAll($con);
        }
		
		
		
		
		public static function clean($value){
			$value=mb_strtolower($value, 'UTF-8');

			$value = str_replace("'", "", $value);
			$value = str_replace(".", "", $value);
			$value = htmlentities($value, ENT_NOQUOTES, 'utf-8');
			$value = preg_replace('#\&([A-za-z])(?:acute|cedil|circ|grave|ring|tilde|uml)\;#', '\1', $value);
			$value = preg_replace('#\&([A-za-z]{2})(?:lig)\;#', '\1', $value); // pour les ligatures e.g. '?'
			$value = preg_replace('#\&[^;]+\;#', '', $value); // supprime les autres caract?res
			$value = preg_replace('/\s/', '', $value); //supprime les espaces

			
			$value = preg_replace("#[^a-z0-9.]#", "", $value);
			return $value;
		}
		
		public static function cleanAccent($value){
			$value=mb_strtolower($value, 'UTF-8');
			$value = str_replace("'", "", $value);
			$value = str_replace(".", "", $value);
			$value = htmlentities($value, ENT_NOQUOTES, 'utf-8');
			$value = preg_replace('#\&([A-za-z])(?:acute|cedil|circ|grave|ring|tilde|uml)\;#', '\1', $value);
			$value = preg_replace('#\&([A-za-z]{2})(?:lig)\;#', '\1', $value); // pour les ligatures e.g. '?'
			$value = preg_replace('/\s/', '', $value); //supprime les espaces
			
			return $value;
		}
		
		
		
		public static function getNbVideos($pro){
			$crit=new Criteria();
			if($pro){
				$crit->addJoin(VideoproprietairePeer::VIDEO_ID,self::ID, Criteria::LEFT_JOIN);
				$crit->add(VideoproprietairePeer::UTILISATEUR_ID, $pro->getId());
			}
			$videos=self::doSelect($crit);
			return sizeof($videos);
		}
		
		
		public static function getNbFilms($pro){
			$crit=new Criteria();
			$crit->add(self::TYPE,'film');
			if($pro){
				$crit->addJoin(VideoproprietairePeer::VIDEO_ID,self::ID, Criteria::LEFT_JOIN);
				$crit->add(VideoproprietairePeer::UTILISATEUR_ID, $pro->getId());
			}
			$videos=self::doSelect($crit);
			return sizeof($videos);
		}
		
		
		public static function getNbSpectacles($pro){
			$crit=new Criteria();
			$crit->add(self::TYPE,'spectacle');
			if($pro){
				$crit->addJoin(VideoproprietairePeer::VIDEO_ID,self::ID, Criteria::LEFT_JOIN);
				$crit->add(VideoproprietairePeer::UTILISATEUR_ID, $pro->getId());
			}
			$videos=self::doSelect($crit);
			return sizeof($videos);
		}
		
		public static function getNbEpisodesSaison($saison, $pro){
			$crit=new Criteria();
			$crit->add(self::TYPE,'episode');
			$crit->add(VideoPeer::SAISON_ID, $saison->getId());
			if($pro){
				$crit->addJoin(VideoproprietairePeer::VIDEO_ID,self::ID, Criteria::LEFT_JOIN);
				$crit->add(VideoproprietairePeer::UTILISATEUR_ID, $pro->getId());
			}
			$videos=self::doSelect($crit);
			return sizeof($videos);
		}
		
		
		
		
		public static function getDerniersVideos($pro,$nb=15){
			$tab_der_video = Array();
			$var_exist = false;
			$bool = false;
			if(apc_fetch('list_derniers_ajout')){
				$var_exist = true;
				$tab_der_video = apc_fetch('list_derniers_ajout');
				if($pro){
					if(isset($tab_der_video[$pro->getId()])){
						$bool = true;
					}
				}else{
					if(isset($tab_der_video['total'])){
						$bool = true;
					}
				}
			}
			if($bool && $var_exist){
				if($pro){
					$dervideos = array_slice($tab_der_video[$pro->getId()], 0, $nb);
				}else{
					$dervideos = array_slice($tab_der_video['total'], 0, $nb);
				}
			}else{
				$crit=self::getCritDerniersVideos($pro);
				$tab_video = self::doSelect($crit);
				if($pro){
					$tab_der_video[$pro->getId()] = $tab_video;
				}else{
					$tab_der_video['total'] = $tab_video;
				}
				apc_delete('list_derniers_ajout');
				apc_add('list_derniers_ajout', $tab_der_video);
				$dervideos = array_slice($tab_video, 0, $nb);
			}

			return $dervideos;
		}
		
	
		
		public static function getCritDerniersVideos($pro){
			$nb_affichage=200;
			$crit=new Criteria();
			if($pro){
				$crit->addJoin(VideoproprietairePeer::VIDEO_ID,self::ID, Criteria::LEFT_JOIN);
				$crit->add(VideoproprietairePeer::UTILISATEUR_ID, $pro->getId());
				$crit->addDescendingOrderByColumn(VideoproprietairePeer::CREATED_AT);
			}else{
				//$sel=' order by video.created_at DESC';
				$crit->addJoin(self::ID, VideoproprietairePeer::VIDEO_ID, Criteria::LEFT_JOIN);
				//$crit->addDescendingOrderByColumn(self::CREATED_AT);
				$crit->addDescendingOrderByColumn(VideoproprietairePeer::CREATED_AT);
			}
			$subSelect = "
			videoproprietaire.CREATED_AT >= ( NOW( ) - INTERVAL 6 MONTH )
			AND
			(
				(video.type !='episode')
				or video.id IN (
					select E.id from (
										select video.* 
										from video, videoproprietaire 
										where video.type='episode' 
										and video.id = videoproprietaire.video_id 
										and video.saison_id is not NULL 
										order by videoproprietaire.created_at DESC
									) 
					E group by E.saison_id
				)
			)
			";
			$crit->addOr(VideoPeer::ID, $subSelect, Criteria::CUSTOM);
			$crit->SetDistinct();

			return $crit;
		}
		
		public static function getCritMeilleursNotes($pro,$nb=15){ 
			
			$crit=new Criteria();
			
			if($pro){
				$crit->add(VideoproprietairePeer::UTILISATEUR_ID, $pro->getId());
				$crit->addJoin(VideoproprietairePeer::VIDEO_ID,self::ID, Criteria::LEFT_JOIN);
			}
			$crit->addJoin(self::ID, NotevideoadminPeer::VIDEO_ID, Criteria::LEFT_JOIN);
			$crit->addGroupByColumn(NotevideoadminPeer::VIDEO_ID); 
			$crit->addDescendingOrderByColumn('AVG('.NotevideoadminPeer::NOTE.')');
			$crit->addAscendingOrderByColumn(self::TITRE);

			$crit->setLimit($nb);
			return $crit;
		}
		
		
		public static function rechercheFilmAllocine($titre){
			$titre_recherche = $titre;
			
			///////////////////////////////////////////////////////////////////////////
			//Code Pierre (lecture HTML Allocine) -> marche (mais temporaire)
			///////////////////////////////////////////////////////////////////////////
			$allocine = new Allocine();
			
			$recherche = $allocine->search($titre_recherche);
			$tab = Array();
			$nb_reponses=0;
			foreach($recherche as $film){
				$tab[$nb_reponses]['code'] = $film['code'];
				$tab[$nb_reponses]['url_img'] = $film['url_img'];
				if($film['titre']){
					$titre = $film['titre'];
				}else{
					$titre = '';
				}
				$tab[$nb_reponses]['titre'] = $titre;
				$tab[$nb_reponses]['annee'] = $film['annee'];
				$tab[$nb_reponses]['realisateur'] = $film['realisateur'];
				$tab[$nb_reponses]['acteurs'] = $film['acteurs'];
				$nb_reponses++;
			}
			
			/*
			///////////////////////////////////////////////////////////////////////////
			//API Allocine v3 -> marche plus (blocage adresse IP ?)
			///////////////////////////////////////////////////////////////////////////
			
			$allocine = new Allocine(ALLOCINE_PARTNER_KEY, ALLOCINE_SECRET_KEY);
			
			$recherche = $allocine->search($titre_recherche);
			$tab = Array();
			$nb_reponses=0;
			foreach($recherche as $movie){
				$tab[$nb_reponses]['code'] = $movie->code;
				$tab[$nb_reponses]['url_img'] = "http://fr.web.img3.acsta.net/r_75_106/".$movie->poster->path;
				if($movie->title){
					$titre = $movie->title;
				}else{
					$titre = $movie->originalTitle;
				}
				$tab[$nb_reponses]['titre'] = $titre;
				$tab[$nb_reponses]['annee'] = $movie->productionYear;
				$tab[$nb_reponses]['realisateur'] = $movie->castingShort->directors;
				$act = explode(",",$movie->castingShort->actors);
				$tab[$nb_reponses]['acteurs'] = $act[0];
				if($act[1]!=''){
					$tab[$nb_reponses]['acteurs'] .= ','.$act[1];
				}
				$nb_reponses++;
			}
			*/
			
			
			return $tab;
		}
		
		
		public static function InfosFilmAllocine($code){
		
 			$allocine = new Allocine();
						
			$movie = $allocine->get_movie($code); 

			// print_r($movie2);
			$titre = explode(":",$movie->title);
			//$infos['titre'] = utf8_encode(ltrim(rtrim($titre[0])));
			// echo($movie->movie->title);
			$infos['titre'] = ltrim(rtrim($titre[0]));
			//$infos['ss_titre'] = utf8_encode(ltrim(rtrim($titre[1])));
			$infos['ss_titre'] = ltrim(rtrim($titre[1]));
			//$infos['titreOriginal'] = utf8_encode($movie->originalTitle);
			$infos['titreOriginal'] = $movie->originalTitle;
			$infos['annee'] = $movie->productionYear;
			//$infos['resume'] = utf8_encode($movie->synopsis);
			$infos['resume'] = $movie->synopsis;
			$infos['avertissement'] = $movie->movieCertificate->certificate->value;

			$infos['categorie'] = Array();
			foreach($movie->genre as $ge ){
				//$infos['categorie'][] = utf8_encode($ge->value);
				$infos['categorie'][] = $ge->value;
			}
			
			$mots_cle = explode(",",$movie->keywords);
			foreach($mots_cle as $mc){
				//$infos['mot_cle'][] = utf8_encode(ltrim(rtrim($mc)));
				$infos['mot_cle'][] = ltrim(rtrim($mc));
			}
			//$infos['mot_cle'][] = utf8_encode(ltrim(rtrim($movie->originalTitle)));	
			$infos['mot_cle'][] = ltrim(rtrim($movie->originalTitle));			


			//Boucle pour récupérer la bande annonce en francais + Images
			$infos['all_images'] = Array();
			$ba_tab['fr'] = Array();
			$ba_tab['original'] = Array();
			$ba_tab['autre'] = Array();
			$media=$movie->media;
			$bool_fr = false;
			$bool_orig = false;
			$bool_vo = false;
			if(isset($media)){
				$n = 0;
				foreach ($media as $med){
					if($med->type->value=="Bande-annonce"){
					
						$test = substr($med->version->value, 0, 4).'ç'.substr($med->version->value, 6);
						$titre = str_replace($movie->title, '<b>'.$movie->title.'</b>', $med->title);
						if($test=="Français"){
							$ba_tab['fr'][$n]['lien'] = "http://www.allocine.fr/blogvision/".$med->code;
							$ba_tab['fr'][$n]['titre'] = utf8_encode($titre);
						}else if($med->version->original){
							$ba_tab['original'][$n]['lien'] = "http://www.allocine.fr/blogvision/".$med->code;
							$ba_tab['original'][$n]['titre'] = utf8_encode($titre);
						}else{
							$ba_tab['autre'][$n]['lien'] = "http://www.allocine.fr/blogvision/".$med->code;
							$ba_tab['autre'][$n]['titre'] = utf8_encode($titre);
						}
					}else if($med->type->value == "Affiche (autres)" || $med->type->value == "Affiche"){
						$infos['all_images'][] = $med->thumbnail->href;
					}
			$n++;
				}
			}
			$infos['all_bandes_annonce'] = array_merge($ba_tab['fr'], $ba_tab['original'], $ba_tab['autre']);
			while (sizeof($infos['all_bandes_annonce']) > 4) {
				array_pop($infos['all_bandes_annonce']);
			} 
			
			$duree=($movie->runtime)/60;
			$infos['duree'] = $duree;
				
			
			$i=0;
			$k=0;
			$rea=0;
			$nomActeurs=array();
			$codeActeurs=array();
			$natActeurs=array();
			$photoActeurs=array();
			$lieuActeurs=array();
				
			$casting=$movie->castMember;
			$nbPers=sizeof($casting);
			//Boucle pour récuperer le realisateur ainsi que les 8 acteurs principaux du film avec toutes leurs info
			foreach( $casting as $pers ){
				$tot=$pers->person;
				$natActeur=$tot->nationality;
				$activities=$pers->activity;
				
				$castComplet=$allocine->get_person($tot->code,$profile);
				$lieuCast=$castComplet->birthPlace;
						
				$deb=strpos($lieuCast,"(");
				$fin=strpos($lieuCast,")");
				$lieu=substr($lieuCast,-($fin-$deb),($fin-$deb)-1);
				$photo='';
				if($pers->picture){
					$pictures=$pers->picture;
					$photo=$pictures->href;
				}
				
				//On parcours les activités de chaque personnage pour savoir son role dans le film
				foreach($activities as $activity){
					//on recupère les infos d'un seul réalisateur
					$test = substr($activity, 0, 1).'e'.substr($activity, 3);
					if((($test=="Realisateur")&&$rea<1) || (($test=="Realisatrice") && $rea<1)){
						
						//$infos['realisateur']['nom'] = utf8_encode($castComplet->name->family);
						$infos['realisateur']['nom'] = $castComplet->name->family;
						//$infos['realisateur']['prenom'] = utf8_encode($castComplet->name->given);
						$infos['realisateur']['prenom'] = $castComplet->name->given;
						$infos['realisateur']['photo'] = $photo;
						$infos['realisateur']['date_naissance'] = $castComplet->birthDate;
						//$infos['realisateur']['pays'] = utf8_encode($lieu);
						$infos['realisateur']['pays'] = $lieu;
						$rea++;
						
					}
				
					//On recupere les infos des 8 premiers acteurs
					if((($activity=="Acteur")&&$k<8) || (($activity=="Actrice") && $k<8)){
						
						$k++;
						//$acteurTab['nom'] = utf8_encode($castComplet->name->family);
						$acteurTab['nom'] = $castComplet->name->family;
						//$acteurTab['prenom'] = utf8_encode($castComplet->name->given);
						$acteurTab['prenom'] = $castComplet->name->given;
						$acteurTab['photo'] = $photo;
						$acteurTab['date_naissance'] = $castComplet->birthDate;
						//$acteurTab['pays'] = utf8_encode($lieu);
						$acteurTab['pays'] = $lieu;
						
						$infos['acteur'][] = $acteurTab;
					}
				}
				//Important, si on l'enleve, la durée d'execution est multiplié par 10 car la boucle parcours tous les acteurs
				if($rea==1 && $k==8){
					break;
				}
			}
			
			
			///////////////////////////////////////////////////////////////////////////
			//API Allocine v3 -> marche plus (blocage adresse IP ?)
			///////////////////////////////////////////////////////////////////////////
			/*
			$allocine = new Allocine(ALLOCINE_PARTNER_KEY, ALLOCINE_SECRET_KEY);

			//echo $film;
			// Créer l'objet
			// $helper = new AlloHelper;
			$profile = 'large';
			//Envoi de la requête
			
			$movie = $allocine->get_movie($code, $profile);
			// $movie = $helper->movie( $code, $profile );
			//echo "film:";
			//recuperation de tous les genres du film
			//print_r($movie);
			//echo $movie;
			$titre = explode(":",$movie->title);
			//$infos['titre'] = utf8_encode(ltrim(rtrim($titre[0])));
			$infos['titre'] = ltrim(rtrim($titre[0]));
			//$infos['ss_titre'] = utf8_encode(ltrim(rtrim($titre[1])));
			$infos['ss_titre'] = ltrim(rtrim($titre[1]));
			//$infos['titreOriginal'] = utf8_encode($movie->originalTitle);
			$infos['titreOriginal'] = $movie->originalTitle;
			$infos['annee'] = $movie->productionYear;
			//$infos['resume'] = utf8_encode($movie->synopsis);
			$infos['resume'] = $movie->synopsis;
			$infos['avertissement'] = $movie->movieCertificate->certificate->value;

			$infos['categorie'] = Array();
			//echo $infos['resume'];
			foreach($movie->genre as $ge ){
				//$infos['categorie'][] = utf8_encode($ge->value);
				$infos['categorie'][] = $ge->value;
			}
			
			$mots_cle = explode(",",$movie->keywords);
			foreach($mots_cle as $mc){
				//$infos['mot_cle'][] = utf8_encode(ltrim(rtrim($mc)));
				$infos['mot_cle'][] = ltrim(rtrim($mc));
			}
			//$infos['mot_cle'][] = utf8_encode(ltrim(rtrim($movie->originalTitle)));	
			$infos['mot_cle'][] = ltrim(rtrim($movie->originalTitle));			


			//Boucle pour récupérer la bande annonce en francais + Images
			$infos['all_images'] = Array();
			$ba_tab['fr'] = Array();
			$ba_tab['original'] = Array();
			$ba_tab['autre'] = Array();
			$media=$movie->media;
			$bool_fr = false;
			$bool_orig = false;
			$bool_vo = false;
			if(isset($media)){
				$n = 0;
				foreach ($media as $med){
					if($med->type->value=="Bande-annonce"){
					
						$test = substr($med->version->value, 0, 4).'ç'.substr($med->version->value, 6);
						$titre = str_replace($movie->title, '<b>'.$movie->title.'</b>', $med->title);
						if($test=="Français"){
							$ba_tab['fr'][$n]['lien'] = "http://www.allocine.fr/blogvision/".$med->code;
							$ba_tab['fr'][$n]['titre'] = utf8_encode($titre);
						}else if($med->version->original){
							$ba_tab['original'][$n]['lien'] = "http://www.allocine.fr/blogvision/".$med->code;
							$ba_tab['original'][$n]['titre'] = utf8_encode($titre);
						}else{
							$ba_tab['autre'][$n]['lien'] = "http://www.allocine.fr/blogvision/".$med->code;
							$ba_tab['autre'][$n]['titre'] = utf8_encode($titre);
						}
					}else if($med->type->value == "Affiche (autres)" || $med->type->value == "Affiche"){
						$infos['all_images'][] = $med->thumbnail->href;
					}
			$n++;
				}
			}
			$infos['all_bandes_annonce'] = array_merge($ba_tab['fr'], $ba_tab['original'], $ba_tab['autre']);
			while (sizeof($infos['all_bandes_annonce']) > 4) {
				array_pop($infos['all_bandes_annonce']);
			} 
			
			$duree=($movie->runtime)/60;
			$infos['duree'] = $duree;
				
			
			$i=0;
			$k=0;
			$rea=0;
			$nomActeurs=array();
			$codeActeurs=array();
			$natActeurs=array();
			$photoActeurs=array();
			$lieuActeurs=array();
				
			$casting=$movie->castMember;
			$nbPers=sizeof($casting);
			//Boucle pour récuperer le realisateur ainsi que les 8 acteurs principaux du film avec toutes leurs info
			foreach( $casting as $pers ){
				$tot=$pers->person;
				$natActeur=$tot->nationality;
				$activities=$pers->activity;
				
				$castComplet=$allocine->get_person($tot->code,$profile);
				$lieuCast=$castComplet->birthPlace;
						
				$deb=strpos($lieuCast,"(");
				$fin=strpos($lieuCast,")");
				$lieu=substr($lieuCast,-($fin-$deb),($fin-$deb)-1);
				$photo='';
				if($pers->picture){
					$pictures=$pers->picture;
					$photo=$pictures->href;
				}
				
				//On parcours les activités de chaque personnage pour savoir son role dans le film
				foreach($activities as $activity){
					//on recupère les infos d'un seul réalisateur
					$test = substr($activity, 0, 1).'e'.substr($activity, 3);
					if((($test=="Realisateur")&&$rea<1) || (($test=="Realisatrice") && $rea<1)){
						
						//$infos['realisateur']['nom'] = utf8_encode($castComplet->name->family);
						$infos['realisateur']['nom'] = $castComplet->name->family;
						//$infos['realisateur']['prenom'] = utf8_encode($castComplet->name->given);
						$infos['realisateur']['prenom'] = $castComplet->name->given;
						$infos['realisateur']['photo'] = $photo;
						$infos['realisateur']['date_naissance'] = $castComplet->birthDate;
						//$infos['realisateur']['pays'] = utf8_encode($lieu);
						$infos['realisateur']['pays'] = $lieu;
						$rea++;
						
					}
				
					//On recupere les infos des 8 premiers acteurs
					if((($activity=="Acteur")&&$k<8) || (($activity=="Actrice") && $k<8)){
						
						$k++;
						//$acteurTab['nom'] = utf8_encode($castComplet->name->family);
						$acteurTab['nom'] = $castComplet->name->family;
						//$acteurTab['prenom'] = utf8_encode($castComplet->name->given);
						$acteurTab['prenom'] = $castComplet->name->given;
						$acteurTab['photo'] = $photo;
						$acteurTab['date_naissance'] = $castComplet->birthDate;
						//$acteurTab['pays'] = utf8_encode($lieu);
						$acteurTab['pays'] = $lieu;
						
						$infos['acteur'][] = $acteurTab;
					}
				}
				//Important, si on l'enleve, la durée d'execution est multiplié par 10 car la boucle parcours tous les acteurs
				if($rea==1 && $k==8){
					break;
				}
			}
			*/
			return $infos;
		}
		
		public static function verifExiste($type, $titre_clean){
			if($type!="episode"){
				$crit=new Criteria();
				$crit->add(VideoPeer::TYPE, $type);
				$crit->add(VideoPeer::TITRE_CLEAN, $titre_clean);
				$video = VideoPeer::doSelect($crit);
				if($video){
					$return = $video[0];
				}else{
					$return = false;
				}
			}else{
				$return = false;
			}
			return $return;
	   }  
	   
		public static function getPager($tab, $page_act, $nb_per_page){
			
			$nb_list_start = 0; 
			if($page_act>1){
				$nb_list_start = $nb_per_page * $page_act - $nb_per_page; 
			}
			$nb_pages = ceil(sizeof($tab)/$nb_per_page);
			$tab_page_act = array_slice($tab, $nb_list_start, $nb_per_page);
			
			$nb_page_inf_sup = 4;
			if($page_act != 1 && $page_act != $nb_pages){
				$plus_sup = 0;
				$nbInf = $page_act-2;
				if($nbInf>=$nb_page_inf_sup/2){
					$nbInf = $nb_page_inf_sup/2;
				}else{
					if($nbInf<0){
						$nbInf = 0;
					}
					$plus_sup = ($nb_page_inf_sup/2) - $nbInf;
				}
				
				$nbSup = ($nb_pages+1)-$page_act;
				if($nbSup>=$nb_page_inf_sup/2){
					$nbSup = ($nb_page_inf_sup/2)+$plus_sup;
				}else{
					if($nbSup<0){
						$nbSup = 0;
					}
					$nbInf = $nb_page_inf_sup - $nbSup;
				}
			}else if($page_act == 1){
				$nbInf = 0;
				$nbSup = $nb_page_inf_sup+1;
			}else if($page_act == $nb_pages){
				$nbInf = $nb_page_inf_sup+1;
				$nbSup = 0;
			}
			$pageInf = $page_act - $nbInf;
			$pageSup = $page_act + $nbSup;
			if($pageInf<1){
				$pageInf=1;
			}
			if($pageSup>$nb_pages){
				$pageSup=$nb_pages;
			}
			if($pageInf <= 1+($nb_page_inf_sup/2) && $pageInf>1){
				$pageInf--;
			}
			if($pageSup >= $nb_pages-($nb_page_inf_sup/2) && $pageSup < $nb_pages){
				$pageSup++;
			}
			if($nb_pages>1){
				$pager['haveToPaginate'] = true;
			}else{
				$pager['haveToPaginate'] = false;
			}
			$pager['getResults'] = $tab;
			$pager['getResultsPageAct'] = $tab_page_act;
			$pager['getPage'] = $page_act;
			$pager['pageInf'] = $pageInf;
			$pager['pageSup'] = $pageSup;
			$pager['getLastPage'] = $nb_pages;
			$pager['getNextPage'] = $page_act+1;
			$pager['getPreviousPage'] = $page_act-1;
			return $pager;
	   }
	
	   
	   
	   
	   
		
} // VideoPeer