generator:
  class: sfPropelGenerator
  param:
    model_class:           utilisateur
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              utilisateur
    plural:                utilisateurs
    route_prefix:          utilisateur
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        created_at:  { label: "Crée le "}
        updated_at:  { label: "Modifiée le "}
      list:
        title:  Gestion Utilisateurs
        display:  [nom,prenom,login,pass,date_naissance]
      filter:  ~
      form:
        class: AdminUtilisateurForm
      edit:
        title: Modification Utilisateur <span class="titredyn">"%%prenom%% %%nom%%"</span>
      new:
        title: Nouvel Utilisateur

