generator:
  class: sfPropelGenerator
  param:
    model_class:           saga
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              saga
    plural:                sagas
    route_prefix:          saga
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Gestion Sagas
      filter:  ~
      form:    ~
      edit:    
         title: Modification Saga <span class="titredyn">"%%titre%%"</span>
      new:
         title: Nouvel Saga
