generator:
  class: sfPropelGenerator
  param:
    model_class:           nationalite
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              nationalite
    plural:                nationalites
    route_prefix:          nationalite
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Gestion Nationnalites
      filter:  ~
      form:    ~
      edit:    
         title: Modification Nationnalite <span class="titredyn">"%%pays%%"</span>
      new:
         title: Nouvel Nationnalite
