generator:
  class: sfPropelGenerator
  param:
    model_class:           qualite
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              qualite
    plural:                qualites
    route_prefix:          qualite
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Gestion Qualites
      filter:  ~
      form:    ~
      edit:    
         title: Modification Qualite <span class="titredyn">"%%nom%%"</span>
      new:
         title: Nouvel Qualite
