generator:
  class: sfPropelGenerator
  param:
    model_class:           film
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              film
    plural:                films
    route_prefix:          film
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        is_public: { label: "Public?" }
        filmproprietaire_list: { label: "Propriétaire(s)" }
        acteurfilm_list: { label: "Acteurs" }
        categoriefilm_list: { label: "Catégorie(s)" }
        created_at:  { label: "Crée le "}
        updated_at:  { label: "Modifiée le "}
      list:
        title:  Gestion Films
        display:  [_image,titre,qualite,version,duree,annee_sortie,_proprietaires]
        sort: [created_at, desc]
        batch_actions: 
           _delete: ~ 
           ajouter_a_aurel: ~ 
           ajouter_a_pierre: ~ 
           maj: ~
      filter:  ~
      form:
        class: AdminFilmForm
      edit:
        title: Modification Film <span class="titredyn">"%%titre%%"</span>
      new:
        title: Nouveau Film
